# ==========================================
# WHAT IS THIS FILE?
# ------------------------------------------
# This file contains all database operations.
#
# CRUD means:
#
# C -> Create
# R -> Read
# U -> Update
# D -> Delete
#
# WHY DO WE NEED IT?
# ------------------------------------------
# Instead of writing database code inside
# API routes, we keep it here.
#
# This makes the project clean and easier
# to maintain.
# ==========================================

# Import SQLAlchemy Session
# Session is used to communicate with the database.
from sqlalchemy.orm import Session

# Import Task model (Database Table)
from app.models import Task

# Import Pydantic Schemas
from app.schemas import TaskCreate, TaskUpdate, TaskPatch


# ==========================================
# CREATE TASK
# ==========================================
# Inserts a new task into the database.
#
# SQL Equivalent:
#
# INSERT INTO tasks(...)
#
def create_task(db: Session, task: TaskCreate):

    # Create a Task object
    db_task = Task(

        title=task.title,

        description=task.description
    )

    # Add the object to the session
    db.add(db_task)

    # Save the data permanently
    db.commit()

    # Refresh the object to get values
    # generated by the database
    # (Example: id)
    db.refresh(db_task)

    return db_task


# ==========================================
# GET ALL TASKS
# ==========================================
# Returns every task from the database.
#
# SQL:
#
# SELECT * FROM tasks;
#
def get_tasks(db: Session):

    return db.query(Task).all()


# ==========================================
# GET SINGLE TASK
# ==========================================
# Returns one task by id.
#
# SQL:
#
# SELECT * FROM tasks
# WHERE id = ?
#
def get_task(db: Session, task_id: int):

    return db.query(Task).filter(Task.id == task_id).first()


# ==========================================
# UPDATE TASK
# ==========================================
#
# SQL:
#
# UPDATE tasks
#

# ==========================================
# UPDATE TASK (PUT)
# ==========================================
# Replaces the entire task.
#
# SQL:
#
# UPDATE tasks
#
# All fields must be provided.
def update_task(
    db: Session,
    task_id: int,
    task: TaskUpdate
):

    db_task = get_task(db, task_id)

    if db_task:

        db_task.title = task.title

        db_task.description = task.description

        db_task.status = task.status

        db.commit()

        db.refresh(db_task)

    return db_task

# ==========================================
# PATCH TASK
# ==========================================
# Partially updates an existing task.
#
# SQL:
#
# UPDATE tasks
# SET only_the_provided_columns
# WHERE id = ?
#
# Unlike PUT, PATCH updates only the fields
# sent by the client.
#
# Example:
#
# {
#     "status": "Completed"
# }
#
def patch_task(
    db: Session,
    task_id: int,
    task: TaskPatch
):

    # Get the existing task from the database
    db_task = get_task(db, task_id)

    # Return None if the task doesn't exist
    if not db_task:
        return None

    # Convert only the fields sent by the client
    # into a dictionary.
    #
    # Example:
    #
    # Request:
    # {
    #     "status":"Completed"
    # }
    #
    # update_data becomes:
    #
    # {
    #     "status":"Completed"
    # }
    #
    update_data = task.model_dump(exclude_unset=True)

    # Update only the provided fields
    for key, value in update_data.items():
        setattr(db_task, key, value)

    # Save changes to the database
    db.commit()

    # Refresh the object
    db.refresh(db_task)

    return db_task

# ==========================================
# DELETE TASK
# ==========================================
#
# SQL:
#
# DELETE FROM tasks
#
def delete_task(
    db: Session,
    task_id: int
):

    db_task = get_task(db, task_id)

    if db_task:

        db.delete(db_task)

        db.commit()

    return db_task